name: improv-assist

services:
  improv-assist-frontend:
    image: ghcr.io/gnueole/improv-assist:latest
    container_name: improv-assist-frontend-prod
    restart: unless-stopped
    environment:
      - PORT=3000
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - GOOGLE_TAG_ID=${GOOGLE_TAG_ID}
      - NEXT_PUBLIC_GA_ID=${NEXT_PUBLIC_GA_ID}
    networks:
      - eole_shared_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.improv.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.improv.entrypoints=websecure"
      - "traefik.http.routers.improv.tls=true"
      - "traefik.http.routers.improv.tls.certresolver=letsencrypt"
      - "traefik.http.services.improv.loadbalancer.server.port=3000"

networks:
  eole_shared_network:
    name: ${DOCKER_NETWORK_NAME}
    external: ${DOCKER_NETWORK_EXTERNAL}
